#pragma once

#include <object.hpp>
#include <utility.hpp>

namespace Raytracing {

    /**
     * @brief This class represents a full transformation formed by the chain of several 'smaller' transformations.
     * This will be automatically generated by the interpreter.
     */
    class Fulltransform : public Object
    {
    public:
        Utility::Matrix4x4 matrix;
        Utility::Matrix4x4 invmatrix;
        std::shared_ptr<Raytracing::Object> obj;
        /**
         * @brief Construct a new Fulltransform object
         * 
         * @param mat The matrix represented by the full transformation
         * @param invmat The inverse of the given matrix
         */
        Fulltransform(Utility::Matrix4x4 mat, Utility::Matrix4x4 invmat) : matrix(mat), invmatrix(invmat)
            { this->_type = ObjectType::Fulltransform; }
    };

}